config/routes.rb
Cta::Application.routes.draw do
  resources :bus_boardings

  get 'bus_aggs' => 'bus_boardings#bus_aggs'

  root 'bus_boardings#bus_aggs'

end

app/models/bus_boarding.rb
class BusBoarding < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bus_boardings_controller.rb
class BusBoardingsController < ApplicationController
  before_action :set_bus_boarding, only: [:show, :edit, :update, :destroy]

  # GET /bus_boardings
  # GET /bus_boardings.json
  def index
    @bus_boardings = BusBoarding.all
  end

  def bus_aggs
    @count = BusBoarding.count
    @avg_boardings = BusBoarding.average("boardings")
    @top_five_boardings = BusBoarding.order("boardings DESC").limit(5)
  end

  # GET /bus_boardings/1
  # GET /bus_boardings/1.json
  def show
  end

  # GET /bus_boardings/new
  def new
    @bus_boarding = BusBoarding.new
  end

  # GET /bus_boardings/1/edit
  def edit
  end

  # POST /bus_boardings
  # POST /bus_boardings.json
  def create
    @bus_boarding = BusBoarding.new(bus_boarding_params)

    respond_to do |format|
      if @bus_boarding.save
        format.html { redirect_to @bus_boarding, notice: 'Bus boarding was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bus_boarding }
      else
        format.html { render action: 'new' }
        format.json { render json: @bus_boarding.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bus_boardings/1
  # PATCH/PUT /bus_boardings/1.json
  def update
    respond_to do |format|
      if @bus_boarding.update(bus_boarding_params)
        format.html { redirect_to @bus_boarding, notice: 'Bus boarding was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bus_boarding.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bus_boardings/1
  # DELETE /bus_boardings/1.json
  def destroy
    @bus_boarding.destroy
    respond_to do |format|
      format.html { redirect_to bus_boardings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bus_boarding
      @bus_boarding = BusBoarding.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bus_boarding_params
      params.require(:bus_boarding).permit(:stop_id, :on_street, :cross_street, :routes, :boardings, :alightings, :month_beginning, :daytype, :longitude, :latitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bus_boardings_helper.rb
module BusBoardingsHelper
end

app/views/bus_boardings/_form.html.erb
<%= form_for(@bus_boarding) do |f| %>
  <% if @bus_boarding.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bus_boarding.errors.count, "error") %> prohibited this bus_boarding from being saved:</h2>

      <ul>
      <% @bus_boarding.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :stop_id %><br>
    <%= f.text_field :stop_id %>
  </div>
  <div class="field">
    <%= f.label :on_street %><br>
    <%= f.text_field :on_street %>
  </div>
  <div class="field">
    <%= f.label :cross_street %><br>
    <%= f.text_field :cross_street %>
  </div>
  <div class="field">
    <%= f.label :routes %><br>
    <%= f.text_field :routes %>
  </div>
  <div class="field">
    <%= f.label :boardings %><br>
    <%= f.text_field :boardings %>
  </div>
  <div class="field">
    <%= f.label :alightings %><br>
    <%= f.text_field :alightings %>
  </div>
  <div class="field">
    <%= f.label :month_beginning %><br>
    <%= f.datetime_select :month_beginning %>
  </div>
  <div class="field">
    <%= f.label :daytype %><br>
    <%= f.text_field :daytype %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bus_boardings/bus_aggs.html.erb
<h1>bus_aggs !!! </h1>

<style type="text/css">
  html { height: 100% }
  body { height: 100%; margin: 0; padding: 0 }
  #map-canvas { height: 100% }
</style>
<script type="text/javascript"
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCX4vt2G-KVYoqM7gYhs5q1uL0VZ-AjTPY&sensor=false">
</script>
<script type="text/javascript">
  function initialize() {
    var mapOptions = {
      center: new google.maps.LatLng(41.8813, -87.6978),
      zoom: 11,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    var map = new google.maps.Map(document.getElementById("map-canvas"),
        mapOptions);

    var locations = [
    <% @top_five_boardings.each do |bus_boarding| %>
      ['<%=bus_boarding.cross_street %>', <%=bus_boarding.latitude %>, <%=bus_boarding.longitude %>, 4],
      <%end%>
    ];

    var infowindow = new google.maps.InfoWindow();

    var marker, i;

    for (i = 0; i < locations.length; i++) {
      marker = new google.maps.Marker({
        position: new google.maps.LatLng(locations[i][1], locations[i][2]),
        map: map
      });

      google.maps.event.addListener(marker, 'click', (function(marker, i) {
        return function() {
          infowindow.setContent(locations[i][0]);
          infowindow.open(map, marker);
        }
      })(marker, i));
    }

  }
  google.maps.event.addDomListener(window, 'load', initialize);
</script>

<p>Number bus boarding records <%= @count %></p>

<p>Average number of boardings acrross all data <%= @avg_boardings %> </p>


<h2>Top five</h2>
<table>
  <thead>
    <tr>
      <th>Stop</th>
      <th>On street</th>
      <th>Cross street</th>
      <th>Routes</th>
      <th>Boardings</th>
      <th>Alightings</th>
      <th>Month beginning</th>
      <th>Daytype</th>
      <th>Longitude</th>
      <th>Latitude</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @top_five_boardings.each do |bus_boarding| %>
      <tr>
        <td><%= bus_boarding.stop_id %></td>
        <td><%= bus_boarding.on_street %></td>
        <td><%= bus_boarding.cross_street %></td>
        <td><%= bus_boarding.routes %></td>
        <td><%= bus_boarding.boardings %></td>
        <td><%= bus_boarding.alightings %></td>
        <td><%= bus_boarding.month_beginning %></td>
        <td><%= bus_boarding.daytype %></td>
        <td><%= bus_boarding.longitude %></td>
        <td><%= bus_boarding.latitude %></td>
        <td><%= link_to 'Show', bus_boarding %></td>
        <td><%= link_to 'Edit', edit_bus_boarding_path(bus_boarding) %></td>
        <td><%= link_to 'Destroy', bus_boarding, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2>Top five on Map</h2>
<body>
  <div id="map-canvas"/>
</body>

app/views/bus_boardings/edit.html.erb
<h1>Editing bus_boarding</h1>

<%= render 'form' %>

<%= link_to 'Show', @bus_boarding %> |
<%= link_to 'Back', bus_boardings_path %>

app/views/bus_boardings/index.html.erb
<h1>Listing bus_boardings</h1>

<table>
  <thead>
    <tr>
      <th>Stop</th>
      <th>On street</th>
      <th>Cross street</th>
      <th>Routes</th>
      <th>Boardings</th>
      <th>Alightings</th>
      <th>Month beginning</th>
      <th>Daytype</th>
      <th>Longitude</th>
      <th>Latitude</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bus_boardings.each do |bus_boarding| %>
      <tr>
        <td><%= bus_boarding.stop_id %></td>
        <td><%= bus_boarding.on_street %></td>
        <td><%= bus_boarding.cross_street %></td>
        <td><%= bus_boarding.routes %></td>
        <td><%= bus_boarding.boardings %></td>
        <td><%= bus_boarding.alightings %></td>
        <td><%= bus_boarding.month_beginning %></td>
        <td><%= bus_boarding.daytype %></td>
        <td><%= bus_boarding.longitude %></td>
        <td><%= bus_boarding.latitude %></td>
        <td><%= link_to 'Show', bus_boarding %></td>
        <td><%= link_to 'Edit', edit_bus_boarding_path(bus_boarding) %></td>
        <td><%= link_to 'Destroy', bus_boarding, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bus boarding', new_bus_boarding_path %>

app/views/bus_boardings/new.html.erb
<h1>New bus_boarding</h1>

<%= render 'form' %>

<%= link_to 'Back', bus_boardings_path %>

app/views/bus_boardings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Stop:</strong>
  <%= @bus_boarding.stop_id %>
</p>

<p>
  <strong>On street:</strong>
  <%= @bus_boarding.on_street %>
</p>

<p>
  <strong>Cross street:</strong>
  <%= @bus_boarding.cross_street %>
</p>

<p>
  <strong>Routes:</strong>
  <%= @bus_boarding.routes %>
</p>

<p>
  <strong>Boardings:</strong>
  <%= @bus_boarding.boardings %>
</p>

<p>
  <strong>Alightings:</strong>
  <%= @bus_boarding.alightings %>
</p>

<p>
  <strong>Month beginning:</strong>
  <%= @bus_boarding.month_beginning %>
</p>

<p>
  <strong>Daytype:</strong>
  <%= @bus_boarding.daytype %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @bus_boarding.longitude %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @bus_boarding.latitude %>
</p>

<%= link_to 'Edit', edit_bus_boarding_path(@bus_boarding) %> |
<%= link_to 'Back', bus_boardings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cta</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>